spring.application.name=orientaucr
server.port=9999

spring.jackson.time-zone=America/Costa_Rica

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/guides_ucr?serverTimezone=America/Costa_Rica
spring.datasource.username=root
spring.datasource.password=

spring.jpa.generate-ddl=false
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.servlet.multipart.max-file-size=5MB

# Recursos estáticos
spring.web.resources.static-locations=file:uploads/

# Configuración de correo
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=carloarobles535@gmail.com
spring.mail.password=cima efxn kibr ueza
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com

spring.servlet.multipart.enabled=true

jwt.secret=p3JVkYcB4z4+eWx7I6UHDgwts5sj3xNhS9xZ/jc7rbCyPfETf5Sb9WkIu0UeZ3+wPmFVzQYHIKvYg+AfNs+5bg==
jwt.expiration=86400000
jwt.refresh.expiration=86400000


