spring.application.name=orientaucr

# Configuración de la base de datos
spring.datasource.url=jdbc:mysql://${DB_HOST:127.0.0.1}:${DB_PORT:3306}/${DB_NAME:guides_ucr}
spring.datasource.username=${DB_USER:root}
spring.datasource.password=${DB_PASSWORD:}

